import { useState, useEffect } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { Navigate } from 'react-router-dom';
import apiService from '../../services/ApiService';

/**
 * Invoices — S15-4
 * Advertiser-only page showing their billing invoices.
 * Route: /dashboard/advertiser/invoices
 */
export default function Invoices() {
    const { user } = useAuth();

    // Role guard — non-advertisers are redirected
    if (user && user.role !== 'advertiser' && user.role !== 'admin' && user.role !== 'superadmin') {
        return <Navigate to="/dashboard" replace />;
    }

    const [invoices, setInvoices] = useState([]);
    const [loading, setLoading]   = useState(true);
    const [error, setError]       = useState(null);
    const [downloading, setDownloading] = useState(null);

    useEffect(() => {
        apiService.request('GET', '/invoices')
            .then(res => setInvoices(res?.invoices ?? res?.data ?? []))
            .catch(err => setError(err?.response?.data?.error ?? err.message))
            .finally(() => setLoading(false));
    }, []);

    const handleDownload = async (invoiceId) => {
        setDownloading(invoiceId);
        try {
            const data = await apiService.request('GET', `/invoices/${invoiceId}/pdf`);
            // Stub: open JSON in a new tab until real PDF is available
            const blob = new Blob([JSON.stringify(data.invoiceData, null, 2)], { type: 'application/json' });
            const url  = URL.createObjectURL(blob);
            const a    = document.createElement('a');
            a.href     = url;
            a.download = `invoice-${invoiceId}.json`;
            a.click();
            URL.revokeObjectURL(url);
        } catch (err) {
            alert('Download failed: ' + (err?.response?.data?.error ?? err.message));
        } finally {
            setDownloading(null);
        }
    };

    const fmt = (n) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n ?? 0);
    const fmtDate = (d) => d ? new Date(d).toLocaleDateString() : '—';

    // ---- Skeleton ----
    if (loading) {
        return (
            <div className="space-y-4 animate-pulse">
                <div className="h-8 w-40 rounded-lg bg-slate-200 dark:bg-slate-700" />
                {[1, 2, 3].map(i => (
                    <div key={i} className="h-14 rounded-xl bg-slate-100 dark:bg-slate-800" />
                ))}
            </div>
        );
    }

    return (
        <div className="space-y-6">
            {/* Header */}
            <div>
                <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Invoices</h1>
                <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
                    Billing records for your completed ad campaigns.
                </p>
            </div>

            {error && (
                <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
            )}

            {invoices.length === 0 ? (
                /* Empty state */
                <div className="rounded-xl border border-dashed border-slate-300 dark:border-slate-700 p-12 flex flex-col items-center text-center gap-3">
                    <span
                        className="material-symbols-outlined text-[48px] text-slate-300 dark:text-slate-600"
                        aria-hidden="true"
                    >
                        receipt_long
                    </span>
                    <p className="text-sm font-medium text-slate-600 dark:text-slate-400">
                        No invoices yet.
                    </p>
                    <p className="text-xs text-slate-400 max-w-xs">
                        Invoices are generated by the admin after your campaign completes.
                    </p>
                </div>
            ) : (
                <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700">
                    <table className="min-w-full divide-y divide-slate-200 dark:divide-slate-700 text-sm">
                        <thead className="bg-slate-50 dark:bg-slate-800">
                            <tr>
                                {['Campaign', 'Generated', 'Impressions', 'CPM Rate', 'Total', 'Actions'].map(h => (
                                    <th
                                        key={h}
                                        className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400"
                                    >
                                        {h}
                                    </th>
                                ))}
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100 dark:divide-slate-800 bg-white dark:bg-slate-900">
                            {invoices.map(inv => (
                                <tr
                                    key={inv.invoiceId ?? inv.id}
                                    className="hover:bg-slate-50 dark:hover:bg-slate-800/60 transition-colors"
                                >
                                    <td className="px-4 py-3 font-medium text-slate-900 dark:text-white">
                                        {inv.campaignId}
                                    </td>
                                    <td className="px-4 py-3 text-slate-500 dark:text-slate-400 tabular-nums">
                                        {fmtDate(inv.generatedAt)}
                                    </td>
                                    <td className="px-4 py-3 text-slate-500 dark:text-slate-400 tabular-nums">
                                        {(inv.impressionsDelivered ?? 0).toLocaleString()}
                                    </td>
                                    <td className="px-4 py-3 text-slate-500 dark:text-slate-400 tabular-nums">
                                        ${inv.cpmRate?.toFixed(2)}
                                    </td>
                                    <td className="px-4 py-3 font-semibold text-slate-900 dark:text-white tabular-nums">
                                        {fmt(inv.amount)}
                                    </td>
                                    <td className="px-4 py-3">
                                        <button
                                            data-testid="invoice-download-btn"
                                            onClick={() => handleDownload(inv.invoiceId ?? inv.id)}
                                            disabled={downloading === (inv.invoiceId ?? inv.id)}
                                            className="inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline disabled:opacity-50"
                                            aria-label={`Download invoice for campaign ${inv.campaignId}`}
                                        >
                                            <span className="material-symbols-outlined text-[14px]" aria-hidden="true">download</span>
                                            {downloading === (inv.invoiceId ?? inv.id) ? 'Downloading…' : 'Download'}
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}
