#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=12

# Local dev env lives in .env.development, per the header of .env.example.
ENV_FILE=".env.development"

EXPECTED_PROJECT="${EXPECTED_PROJECT:-softomedia-live-2026}"
REGION="us-central1"          # cloudbuild.yaml substitutions._REGION
AR_REPO="softomedia"          # cloudbuild.yaml substitutions._ARTIFACT_REGISTRY
SVC_ADSERVER="ad-server"      # cloudbuild.yaml substitutions._SERVICE_ADSERVER
SVC_CLIENT="client-app"       # cloudbuild.yaml substitutions._SERVICE_CLIENT
EMULATOR_PROJECT="softomedia-demo"   # package.json test:rules --project

# have CMD: is CMD runnable? Tolerates the .cmd/.exe shims Git Bash sees on Windows.
have() {
  command -v "$1" >/dev/null 2>&1 ||
  command -v "$1.cmd" >/dev/null 2>&1 ||
  command -v "$1.exe" >/dev/null 2>&1
}

# gc / fb: call gcloud / firebase by whatever name this platform exposes.
gc() {
  if   command -v gcloud     >/dev/null 2>&1; then gcloud "$@"
  elif command -v gcloud.cmd >/dev/null 2>&1; then gcloud.cmd "$@"
  else warn "gcloud is not installed; re-run stage 1."; return 127; fi
}

banner "Softomedia rollout: local + Google Cloud"

# -- 1 ---------------------------------------------------------------------
stage "Tooling"
say "Checking every command the rollout needs."
printf '\n'
for c in node npm docker gh; do
  if have "$c"; then say "  [ok] $c"; else warn "$c is missing"; SKIPPED+=("install $c"); fi
done

if have gcloud; then
  say "  [ok] gcloud"
else
  printf '\n'; warn "gcloud is NOT installed. It is required from stage 2 onward."
  open_url "https://cloud.google.com/sdk/docs/install"
  step "Install the Google Cloud CLI, then reopen this terminal so PATH picks it up."
  pause "Press Enter once gcloud is installed."
  have gcloud || { warn "still not on PATH. Re-run this wizard from a fresh terminal."; exit 1; }
  say "  [ok] gcloud"
fi

if have firebase; then
  say "  [ok] firebase"
else
  printf '\n'; warn "firebase-tools is missing. Stage 10 (emulator) and firestore:rules need it."
  if confirm "Install it now with 'npm install -g firebase-tools'?"; then
    npm install -g firebase-tools || warn "install failed; do it by hand."
  else
    SKIPPED+=("npm install -g firebase-tools")
  fi
fi

if have java; then
  say "  [ok] java (the Firestore emulator needs a JVM)"
else
  warn "java is missing. 'npm run test:rules' cannot start the Firestore emulator."
  note "Install a JDK 11+ (e.g. Temurin) before stage 10."
  SKIPPED+=("install a JDK 11+ for the Firestore emulator")
fi
printf '\n'
pause

# -- 2 ---------------------------------------------------------------------
stage "Authenticate to Google Cloud"
say "Two logins: your user account, then application-default credentials."
note "ADC is what local Firestore access and the Admin SDK read."
printf '\n'
step "A browser window opens. Pick the account with access to the deploy project."
pause "Press Enter to run 'gcloud auth login'."
gc auth login || warn "login did not complete cleanly."
printf '\n'
step "Now the same again for application-default credentials."
pause "Press Enter to run 'gcloud auth application-default login'."
gc auth application-default login || warn "ADC login did not complete cleanly."
printf '\n'
say "Signed in as:"
gc auth list --filter=status:ACTIVE --format="value(account)" 2>/dev/null | sed 's/^/    /' || true
printf '\n'
pause

# -- 3 ---------------------------------------------------------------------
stage "Project guard"
warn "sre-reports/report-2026-06-22T03-52-30.md records a verification run that"
warn "executed against a DIFFERENT project than intended. That report's own"
warn "assessment: risk of severe cross-project contamination. It was never fixed."
printf '\n'
say "Nothing past this stage runs until the active project matches exactly."
printf '\n'
note "Heads up: the repo spells the project two ways. cloudbuild.yaml line 1 says"
note "softomedia-live-2026; .env.example says softomedia-live2026. Only one is"
note "real. Pick from the live list below, then fix the other file."
printf '\n'
say "Projects visible to your account:"
gc projects list --format="value(projectId)" 2>/dev/null | sed 's/^/    /' || warn "couldn't list projects."
printf '\n'
ask PROJECT_ID "Project ID to deploy to [default: $EXPECTED_PROJECT]:"
[[ -z "${PROJECT_ID:-}" ]] && PROJECT_ID="$EXPECTED_PROJECT"

gc config set project "$PROJECT_ID" >/dev/null 2>&1 || true
ACTIVE_PROJECT=$(gc config get-value project 2>/dev/null | tr -d '[:space:]' || echo "")

if [[ "$ACTIVE_PROJECT" != "$PROJECT_ID" ]]; then
  printf '\n  %s[STOP]%s\n' "$BOLD$RED" "$RESET"
  say "  requested: $PROJECT_ID"
  say "  active:    ${ACTIVE_PROJECT:-<none>}"
  say "These must match. Fix with: gcloud config set project $PROJECT_ID"
  exit 1
fi
printf '\n  %s[ok] active project is %s%s\n' "$GREEN" "$ACTIVE_PROJECT" "$RESET"
write_env PROJECT_ID "$PROJECT_ID"
printf '\n'
pause

# -- 4 ---------------------------------------------------------------------
stage "Enable APIs"
say "cloudbuild.yaml needs all five of these enabled on $PROJECT_ID."
printf '\n'
for api in cloudbuild.googleapis.com run.googleapis.com \
           artifactregistry.googleapis.com firestore.googleapis.com \
           secretmanager.googleapis.com; do
  say "  - $api"
done
printf '\n'
if confirm "Enable them now?"; then
  gc services enable \
    cloudbuild.googleapis.com run.googleapis.com \
    artifactregistry.googleapis.com firestore.googleapis.com \
    secretmanager.googleapis.com --project "$PROJECT_ID" \
    || warn "enable failed; you may lack serviceusage.services.enable."
else
  SKIPPED+=("enable the five required APIs on $PROJECT_ID")
fi
printf '\n'
pause

# -- 5 ---------------------------------------------------------------------
stage "Artifact Registry"
say "cloudbuild.yaml pushes both images to:"
note "  $REGION-docker.pkg.dev/$PROJECT_ID/$AR_REPO/{$SVC_ADSERVER,$SVC_CLIENT}"
say "The '$AR_REPO' repository must exist in $REGION or every push fails."
printf '\n'
if gc artifacts repositories describe "$AR_REPO" --location "$REGION" \
     --project "$PROJECT_ID" >/dev/null 2>&1; then
  printf '  %s[ok] repository %s already exists in %s%s\n' "$GREEN" "$AR_REPO" "$REGION" "$RESET"
elif confirm "Repository not found. Create it now?"; then
  gc artifacts repositories create "$AR_REPO" \
    --repository-format=docker --location "$REGION" \
    --description="Softomedia service images" --project "$PROJECT_ID" \
    || warn "create failed."
else
  SKIPPED+=("create Artifact Registry repo $AR_REPO in $REGION")
fi
printf '\n'
pause

# -- 6 ---------------------------------------------------------------------
stage "Secret Manager"
say "cloudbuild.yaml step 0 FAILS THE BUILD unless both secrets already exist."
note "It checks with 'gcloud secrets describe' before anything is built."
printf '\n'
say "JWT_SECRET: generating a fresh 32-byte random value."
JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
if gc secrets describe JWT_SECRET --project "$PROJECT_ID" >/dev/null 2>&1; then
  if confirm "JWT_SECRET exists. Add a NEW version (this invalidates live sessions)?"; then
    printf '%s' "$JWT_SECRET" | gc secrets versions add JWT_SECRET --data-file=- --project "$PROJECT_ID" || warn "failed."
  else
    say "  keeping the existing JWT_SECRET."
    JWT_SECRET=""
  fi
else
  printf '%s' "$JWT_SECRET" | gc secrets create JWT_SECRET --data-file=- --replication-policy=automatic --project "$PROJECT_ID" || warn "failed."
fi
printf '\n'
say "GEMINI_API_KEY: needed by the AI features."
open_url "https://aistudio.google.com/app/apikey"
step "Create or copy an API key on that page."
ask_secret GEMINI_API_KEY "Paste the Gemini API key (Enter to skip):"
if [[ -n "${GEMINI_API_KEY:-}" ]]; then
  if gc secrets describe GEMINI_API_KEY --project "$PROJECT_ID" >/dev/null 2>&1; then
    printf '%s' "$GEMINI_API_KEY" | gc secrets versions add GEMINI_API_KEY --data-file=- --project "$PROJECT_ID" || warn "failed."
  else
    printf '%s' "$GEMINI_API_KEY" | gc secrets create GEMINI_API_KEY --data-file=- --replication-policy=automatic --project "$PROJECT_ID" || warn "failed."
  fi
else
  SKIPPED+=("create Secret Manager secret GEMINI_API_KEY (the cloud build fails without it)")
fi
printf '\n'
pause

# -- 7 ---------------------------------------------------------------------
stage "Service account and IAM"
say "The Cloud Build service account performs the deploy, so it needs a role"
say "for every action cloudbuild.yaml takes."
printf '\n'
PROJECT_NUMBER=$(gc projects describe "$PROJECT_ID" --format="value(projectNumber)" 2>/dev/null | tr -d '[:space:]' || echo "")
if [[ -z "$PROJECT_NUMBER" ]]; then
  warn "couldn't read the project number; grant these by hand in the IAM console."
  SKIPPED+=("grant Cloud Build SA: run.admin, iam.serviceAccountUser, secretmanager.secretAccessor, artifactregistry.writer, datastore.indexAdmin")
else
  CB_SA="${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com"
  say "Cloud Build SA: $CB_SA"
  printf '\n'
  say "  roles/run.admin                      deploy both Cloud Run services"
  say "  roles/iam.serviceAccountUser         act as the runtime SA"
  say "  roles/secretmanager.secretAccessor   read JWT_SECRET, GEMINI_API_KEY"
  say "  roles/artifactregistry.writer        push images"
  say "  roles/datastore.indexAdmin           deploy Firestore indexes"
  printf '\n'
  if confirm "Grant all five to $CB_SA?"; then
    for role in roles/run.admin roles/iam.serviceAccountUser \
                roles/secretmanager.secretAccessor roles/artifactregistry.writer \
                roles/datastore.indexAdmin; do
      if gc projects add-iam-policy-binding "$PROJECT_ID" \
           --member="serviceAccount:${CB_SA}" --role="$role" --condition=None >/dev/null 2>&1; then
        say "  [ok] $role"
      else
        warn "  failed: $role"
      fi
    done
  else
    SKIPPED+=("grant the five IAM roles to $CB_SA")
  fi
fi
printf '\n'
pause

# -- 8 ---------------------------------------------------------------------
stage "Cloud Build trigger"
warn "cloudbuild.yaml defaults _ALLOW_DEMO_MODE to 'true'. Its own comment says"
warn "to set it to 'false' in production triggers. Nothing enforces that."
printf '\n'
say "The demo-token bypass must be OFF for any production trigger."
note "Set substitution _ALLOW_DEMO_MODE=false when you create the trigger."
printf '\n'
open_url "https://console.cloud.google.com/cloud-build/triggers?project=$PROJECT_ID"
step "Create trigger -> connect the repository -> Cloud Build config: cloudbuild.yaml"
step "Under 'Substitution variables', add _ALLOW_DEMO_MODE = false"
step "Leave _REGION, _ARTIFACT_REGISTRY and the service names at their defaults."
pause "Press Enter once the trigger exists."
printf '\n'
pause

# -- 9 ---------------------------------------------------------------------
stage "Local environment file"
say "Writing $ENV_FILE, the local-dev counterpart of .env.example."
printf '\n'
if [[ -n "${JWT_SECRET:-}" ]]; then
  write_env JWT_SECRET "$JWT_SECRET"
else
  ask_secret JWT_SECRET "JWT_SECRET for local dev (Enter to generate one):"
  [[ -z "${JWT_SECRET:-}" ]] && JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  write_env JWT_SECRET "$JWT_SECRET"
fi
[[ -n "${GEMINI_API_KEY:-}" ]] && write_env GEMINI_API_KEY "$GEMINI_API_KEY"
write_env VITE_API_URL    "http://localhost:8080"
write_env CORS_ORIGINS    "http://localhost:5173,http://localhost:3000"
write_env NODE_ENV        "development"
write_env PORT            "8080"
write_env CLIENT_PORT     "5173"
write_env ALLOW_DEMO_MODE "true"
printf '\n'
note "ALLOW_DEMO_MODE=true is required locally for the Playwright demo-wizard"
note "project. .env.example states auth.js blocks demo mode when"
note "NODE_ENV=production regardless of the flag. Stage 11 is where you find out."
printf '\n'
pause

# -- 10 --------------------------------------------------------------------
stage "Firestore emulator"
say "'npm run test:rules' runs the security-rules suite against the emulator"
say "on project $EMULATOR_PROJECT, port 8090 (firebase.json)."
printf '\n'
warn "firebase.json is UTF-16LE encoded, not UTF-8. If firebase-tools rejects"
warn "it, re-save it as UTF-8 - that is a repo bug, not a setup mistake."
printf '\n'
say "Two index files disagree, which also needs a human decision:"
note "  firebase.json      -> firestore.indexes.json             (root, 2978 B)"
note "  cloudbuild.yaml #6 -> ad-server/firestore.indexes.json   (858 B)"
note "Step 6 is allowFailure:true, so a mismatch deploys silently."
printf '\n'
if have firebase && have java; then
  if confirm "Run the rules suite now?"; then
    npm run test:rules || warn "rules suite failed - capture the output, it is a finding."
  fi
else
  warn "skipping: firebase-tools and/or java missing."
  SKIPPED+=("run 'npm run test:rules' once firebase-tools and a JDK are installed")
fi
printf '\n'
pause

# -- 11 --------------------------------------------------------------------
stage "Prove the local rollout"
say "The local path is proven when install, unit and e2e all pass."
printf '\n'
say "  npm run setup       install all three packages + playwright browsers"
say "  npm run test:unit   jest, inside ad-server"
say "  npm run test:e2e    playwright (runs scripts/test-preflight.js first)"
printf '\n'
if confirm "Run 'npm run setup' now? (slow: it installs browsers)"; then
  npm run setup || warn "setup failed - capture the output."
fi
printf '\n'
if confirm "Run the unit suite?"; then
  npm run test:unit || warn "unit suite failed - capture the output, it is a finding."
fi
printf '\n'
if confirm "Run the e2e suite?"; then
  npm run test:e2e || warn "e2e suite failed - capture the output, it is a finding."
fi
printf '\n'
note "A failure here is evidence for the QA report, not a reason to stop."
printf '\n'
pause

# -- 12 --------------------------------------------------------------------
stage "Prove the Cloud rollout"
say "This submits a real build that deploys to Cloud Run on $PROJECT_ID."
printf '\n'
warn "IRREVERSIBLE: it replaces the running $SVC_ADSERVER and $SVC_CLIENT services."
printf '\n'
say "Guard re-check before anything is submitted:"
ACTIVE_PROJECT=$(gc config get-value project 2>/dev/null | tr -d '[:space:]' || echo "")
if [[ "$ACTIVE_PROJECT" != "$PROJECT_ID" ]]; then
  printf '  %s[STOP] project drifted to %s - refusing to deploy.%s\n' "$RED" "${ACTIVE_PROJECT:-<none>}" "$RESET"
  exit 1
fi
printf '  %s[ok] still %s%s\n\n' "$GREEN" "$ACTIVE_PROJECT" "$RESET"

if confirm "Submit the build with _ALLOW_DEMO_MODE=false?"; then
  gc builds submit --config cloudbuild.yaml \
    --substitutions=_ALLOW_DEMO_MODE=false \
    --project "$PROJECT_ID" \
    || warn "build failed - the log URL above is the evidence."
  printf '\n'
  say "Deployed service URLs:"
  gc run services describe "$SVC_ADSERVER" --region "$REGION" --project "$PROJECT_ID" --format="value(status.url)" 2>/dev/null | sed 's/^/    ad-server:  /' || true
  gc run services describe "$SVC_CLIENT"   --region "$REGION" --project "$PROJECT_ID" --format="value(status.url)" 2>/dev/null | sed 's/^/    client-app: /' || true
  printf '\n'
  note "cloudbuild.yaml polls /health for 60s and fails the build if it never"
  note "returns 200, so a green build IS the health proof."
else
  SKIPPED+=("submit the Cloud Build deploy (stage 12)")
fi
printf '\n'
pause

finish
